### ISSUE TITLE
Get current visitors channel and campaign params

### ISSUE THREAD

**Issue by ChristianaHoJo** [matomo-org/matomo-php-tracker#101]
Hi!
Does the PHP Client for Matomo Analytics Tracking API provide a function to get Infos from current visitor profile  like the channel (e.g. Google, Direct Call ...) and the campaign parameters? Maybe after getting the visitors id. Therefore I found the function  getVisitorId(). 

I would be very happy about any help or a hint! 

Greetings,
Christiana

**Comment by sgiehl** [comment]
Hi Christiana,
You won't be able to access the visitor profile information using the PHP tracker. But depending on the way you implemented the tracking it might give you access on the attribution info using `getAttributionInfo` and some other data, that might be stored in cookies.
If you need something from the visitor profile you might need to query the Matomo API to fetch it yourself.
