### ISSUE TITLE
More virtualization of MatomoTracker class

### ISSUE THREAD

**Issue by Demichev** [matomo-org/matomo-php-tracker#103]
## Summary
May I ask not popular but small feature? We are using MatomoTracker class to emulate user page visits when payment callback is executed. MatomoTracker is poorly virtualized so I overrode the whole sendRequest() method just to replace proxy (getProxy() method is private), add CURLOPT_HTTPHEADER to curl and ['http']['header'] to $stream_options.
It works but each time Matomo is updated I compare code, make changes, etc. 
Can you make getProxy() protected and add empty protected methods for curl options/stream_options?

## Your Environment
* Matomo Version: 4.7.1

**Comment by justinvelluppillai** [comment]
hi @Demichev - thanks for the PR. I have taken a look and also asked @sgiehl to take a look as he has more experience here, so hopefully we can get this merged next week.
