### ISSUE TITLE
Goals attribution only show 'direct' attribution

### ISSUE THREAD

**Issue by johnnybegoodalways** [matomo-org/matomo-php-tracker#106]
Hi!

We've been asked to submit an issue here by the Matomo support team.

We use Matomo Cloud for analytics and to track goal conversions (subscription purchases). We experience that our goals only get 'direct' attribution. See the attached files that show our code.

Here's how a signup/conversion takes place
• A user lands on Onlime.dk via an affiliate (Wordpress)
• The user creates a free account on Onlime.dk (Wordpress)
• The user logs into onlime.dk/user/login and purchases a subscription (Webapp)
• We have set up goals to each subscription purchase, so we should see an entry attribute of ‘Websites’ instead of ‘Direct’.

![Attachment](https://user-images.githubusercontent.com/112384467/187165140-03620d5f-40a8-4721-a801-5c0e7c4cae55.png)
![Onlime matomo tracking script 1 (Wordpress)](https://user-images.githubusercontent.com/112384467/187165154-8be52391-61b4-4831-853b-b0cd586e981e.png)
![Onlime matomo tracking script 2 (webapp)](https://user-images.githubusercontent.com/112384467/187165174-baf8cc63-161a-4acc-addf-4ad148ea3c0d.png)
![Code to track free subscriptions](https://user-images.githubusercontent.com/112384467/187165538-3f7cfc7e-678d-41a0-b18b-a4f8a449f8d6.png)
![Code to track paid subsciptions](https://user-images.githubusercontent.com/112384467/187165541-9dca61e1-eb41-42e0-8a06-c12d16d02431.png)

**Comment by sgiehl** [comment]
@johnnybegoodalways Thanks for creating this issue.
So you are tracking the visitors with javascript initially and do some goal tracking on PHP side afterwards. Right?
Are the goal conversions currently been tracked as new visits or did you implement anything that gives Matomo a link between javascript and php?

**Comment by johnnybegoodalways** [comment]
Hi Sgiehl and thanks for your reply! Hmm, no I don't think we have been aware of having to create at link between the two types of codebases used for tracking. We have setup Matomo for both cookieless and cookie-based tracking and thus assumed we would be able to track across our WP mainsite and the web-app for subscription administration. We'd much appreciate any link or tips to how we proceed!

**Comment by johnnybegoodalways** [comment]
Alright, thanks @sgiehl
