### ISSUE TITLE
Generate a download in Behavior > Downloads

### ISSUE THREAD

**Issue by davidperezgar** [matomo-org/matomo-php-tracker#112]
Hello, 
I'd like to generate a download in Behavior > Downloads. How could I do it?

`$matomo_tracker->doTrackAction( $file, 'download' );`

Does not generate it?

**Comment by sgiehl** [comment]
The call above should track a download, which should be shown in `Behavior > Downloads`.
If that doesn't work for you, maybe try to find some help on our forum at https://forum.matomo.org
Providing some additional details might be helpful for troubleshooting.
