### ISSUE TITLE
Drop support of older php versions?

### ISSUE THREAD

**Issue by Chris53897** [matomo-org/matomo-php-tracker#118]
Are there any plans to drop support for older php versions?

**Comment by LauraTaylorUK** [comment]
I'm not a matomo developer, but here is how I handle PHP version requirements/compatibility at my projects:

1) follow supported PHP versions based on Enterprise Linux (RHEL, Alma, Rocky, Oracle).
2) CentOS 7 with PHP 5.6 is still fully supported till 2024, so support at least that.
3) Once CentOS 7 has reached its EOL, move to the next lesser version: PHP 8.0
4) Support at least PHP 8.0 while its supported by Enterprise Linux (RHEL, Alma, Rocky, Oracle), off the top of my head, its up to 2029!

Sure, the cool kids will be running the latest and greatest version, but those of us living in the finance sector, running sensitive applications that require 8 year stability, we have other requirements. Following Enterprise Linux practices gives the best compatibility for enterprises.

**Comment by Chris53897** [comment]
Of course there are different needs. 
I hope that these companies support the maintainers for there extra work, to support legacy versions.
In general, not limited to this repo.

I noticed your PR to improve code quality. Thanks for that.

**Comment by LauraTaylorUK** [comment]
I'm waiting for CentOS 7 to expire in 2024, then we can begin some serious refactoring with PHP 8.x and avoid using the 7.x series.

About my PR, no problem, just giving back to the community. I hope it gets merged, so I can continue with [PSR compatibility standards](https://www.php-fig.org/psr/), PSR-1 & PSR-12.

**Comment by lutdev** [comment]
@sgiehl @michalkleiner can you close this issue?) Details are in the PR.
