### ISSUE TITLE
Minor edit to documentation

### ISSUE THREAD

**Issue by itscvenk** [matomo-org/matomo-php-tracker#121]
https://developer.matomo.org/api-reference/tracking-api

![image](https://github.com/matomo-org/matomo-php-tracker/assets/117738376/1617c6e4-def8-42f4-8861-134f8edf9eca)

I guess the highlighted text ought to be "defines the User Id", as the visitor Id is set by "_id" right?

Thanks

**Comment by sgiehl** [comment]
No, the `cid` isn't the user id. It's actually some sort of configuration id, which is - if not provided - calculated by creating a hash over some visitor details. The user id should be provided using `uid only.`
For further documentation related issues, you can directly create them in https://github.com/matomo-org/developer-documentation
