### ISSUE TITLE
Creation of dynamic property MatomoTracker::$currentTs is deprecated

### ISSUE THREAD

**Issue by dkossako** [matomo-org/matomo-php-tracker#129]
There are some deprecations in latest version of tracker:

```
Creation of dynamic property MatomoTracker::$currentTs is deprecated
```

Also other properties are affected:

- MatomoTracker::$forcedVisitorId
- MatomoTracker::$requestTimeout
- MatomoTracker::$configCookiePath
- MatomoTracker::$visitCount
- MatomoTracker::$ecommerceLastOrderTimestamp
- MatomoTracker::$doBulkRequests
- MatomoTracker::$incomingTrackerCookies

```
        $this->currentTs = time();
        $this->createTs = $this->currentTs;
        $this->visitCount = 0;
        $this->currentVisitTs = false;
        $this->lastVisitTs = false;
        $this->ecommerceLastOrderTimestamp = false;
```

**Comment by michalkleiner** [comment]
Thanks for raising the issue @dkossako, we will look into adding class variables for the dynamic properties.

**Comment by michalkleiner** [comment]
Can you confirm what version of PHP you're running the tracker on? Is it 8.2?

**Comment by lutdev** [comment]
@sgiehl you have merged my PR, can we tag the new version and close this issue?)

**Comment by michalkleiner** [comment]
@lutdev let's do it together with #132.
