### ISSUE TITLE
Documentation for doTrackAction

### ISSUE THREAD

**Issue by MichiMunich** [matomo-org/matomo-php-tracker#18]
Hi,

referring to this thread https://forum.piwik.org/t/how-to-use-dotrackaction-with-php/17978 i am opening this issue. It would be great if you could extend the documentation for "doTrackAction". PHP tracking works verry well on my WordPress blog except the tracking of outgoing links and downloads. I don't know how to fill the variable $actionUrl with PHP code.

Thanks in advance

**Comment by thenexxuz** [comment]
is this still an issue?

**Comment by MichiMunich** [comment]
Not for me. I switched to the JS tracker.

**Comment by NicoHood** [comment]
I think this can be closed

**Comment by tsteur** [comment]
👍  Should be documented in https://developer.matomo.org/api-reference/PHP-Matomo-Tracker#dotrackaction
