### ISSUE TITLE
implement the fluent interface

### ISSUE THREAD

**Issue by weboperator** [matomo-org/matomo-php-tracker#25]
The function addEcommerceItem() has no return value.

Due to your documentation this function should be called before e.g. doTrackEcommerceOrder() is called.
If you do so you will get 

> Fatal error: Call to a member function doTrackEcommerceOrder() on null

In our opinion you should implement the fluent interface and return the object instance:

```
689 = $this->ecommerceItems[] = array($sku, $name, $category, $price, $quantity);
690 + return $this;
```

Thanks in advance for feedback!
Have a great time!

**Comment by mattab** [comment]
Thanks for the report. Would you please create a pull request for this?
