### ISSUE TITLE
Why the tag @ignore for sendRequest()?

### ISSUE THREAD

**Issue by olleharstedt** [matomo-org/matomo-php-tracker#32]
It would improve documentation to use full PHPDoc for that function, IMO. And instead of `mixed`, `boolean|string` can be used to clearly specify what is returned. I can make another PR for this if you like.

**Comment by sgiehl** [comment]
It's an internal method that should not show up in documentation that is generated using the doc blocks. 
But feel free to create PRs for improving any docblocks where it make sense.
