### ISSUE TITLE
Example on Matomo website has incorrect API usage

### ISSUE THREAD

**Issue by baconbrad** [matomo-org/matomo-php-tracker#33]
Unsure if this is the proper place to report it. But I couldn't find a issue manager for the website. On [this page](https://matomo.org/docs/tracking-api/) the example for 'Method 2: HTTP Request' wrongly uses `MatomoTracker()` instead of `PiwikTracker()`. This will cause the script to fail. While this may be subject to be renamed down the road as of now `PiwikTracker()` is still the correct usage with the current available version of the PHP tracker.

**Comment by NicoHood** [comment]
I guess now the oppisite is true: Piwik must be renamed to matomo

**Comment by tsteur** [comment]
Thanks. This should be fixed now.
