### ISSUE TITLE
Composer: Ambiguous class resolution, "PiwikTracker" was found in both..

### ISSUE THREAD

**Issue by madman-81** [matomo-org/matomo-php-tracker#54]
Composer issues the warning below when generating optimized autoload files:

Warning: Ambiguous class resolution, "PiwikTracker" was found in both "C:\project\vendor/matomo/matomo-php-tracker/.\MatomoTracker.php" and "C:\project\vendor/matomo/matomo-php-tracker/.\PiwikTracker.p
hp", the first will be used.

The solution would be to remove the class declaration from MatomoTracker.php since this included in PiwikTracker.php.

**Comment by tsteur** [comment]
Reopening for now because of https://github.com/matomo-org/matomo-php-tracker/pull/55#issuecomment-570318314
