### ISSUE TITLE
Documentation? Example? How to use?

### ISSUE THREAD

**Issue by thd-fox** [matomo-org/matomo-php-tracker#59]
First, I thank you very much for the awesome matomo tracking software! I'm using it for many years now. Sadly I'm now very disappointed of the current version of this php tracking library :(
I can't find any example, or any installation instructions.
I used your php library for many years now and suddenly it was broken!
Today I tried to update and I was very happy to see you published your library as composer installable.

Please give me a code sample with a basic example that shows how to track with the token auth.

BTW: The reason everything broke is an authentication error.

**Comment by tsteur** [comment]
@sgiehl I suppose not much changed? Basically people can install it same way, or using composer install? And they use MatomoTracker now which is probably the biggest change?

**Comment by tsteur** [comment]
An authentication error should actually not happen I would say. Doubt we changed anything there? 

@thd-fox was the token auth maybe reset in the Matomo UI?

**Comment by robo2bobo** [comment]
I agree, there are no code samples for someone new to copy/paste and get things moving quickly.

Here is something that could be posted on the main readme:

```php

// Required variables
$matomoSiteId = 6;                  // Site ID
$matomoUrl = "https://example.tld"; // Your matomo URL
$matomoToken = "";                  // Your authentication token

// Optional variable
$matomoPageTitle = "";              // The title of the page

// Load object
require_once("MatomoTracker.php");

// Matomo object
$matomoTracker = new MatomoTracker((int)$matomoSiteId, $matomoUrl);

// Set authentication token
$matomoTracker->setTokenAuth($matomoToken);

// Track page view
$matomoTracker->doTrackPageView($matomoPageTitle);

```

**Comment by thd-fox** [comment]
Thank you @tsteur and @robo2bobo I figured out that with your new version of the tracking library all requests are blocked by apache mod_security. I changed my server configuration and now it's working fine.
I suppose your new version will work as expected then. I can't verify it by now. I will soon update and report back to you :)
@robo2bobo's code sample would be very helpful! With this I can confirm I'm using the library correctly :)

**Comment by tsteur** [comment]
@thd-fox do you know what exactly blocked it in mod_security?

**Comment by thd-fox** [comment]
@tsteur I suppose it could be related to your different call method. The old version, which I use right now did not conflict with mod_security. There were standard filters activated, which let all old requests through. The new ones were completely blocked. I couldn't figure out the reason. I simply disabled mod_security.

**Comment by tsteur** [comment]
Cheers @robo2bobo 

Took your example and added it to the readme, also added basic install instructions. Feel free to suggest more or edit readme directly and create a PR 👍
