### ISSUE TITLE
Add possibility to add custom tracking parameter

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo-php-tracker#6]
When a developer builds a plugin, say "Bandwidth", that defines a new tracking parameter, say "bw_bytes", then it is not possible to send this HTTP Tracking API parameter using the PHP Piwik Tracker. There should be the possibility to do this otherwise plugins that define a new dimension are not very useful.

It is to be defined whether we should reset those parameters after each `sendRequest` or not. Maybe we need both behavior

**Comment by mattab** [comment]
This was added in https://github.com/piwik/piwik-php-tracker/pull/15
