### ISSUE TITLE
setGenerationTime() documentation deprecation

### ISSUE THREAD

**Issue by NicoHood** [matomo-org/matomo-php-tracker#82]
As stated in the latest [changelog](https://github.com/matomo-org/matomo-php-tracker/releases/tag/3.0.0) the function `setGenerationTime()` is deprecated. This should be added to the docs.

**Comment by tsteur** [comment]
Hi @NicoHood I've updated the doc in https://github.com/matomo-org/matomo-php-tracker/pull/83 so it will be updated on https://developer.matomo.org/api-reference/PHP-Matomo-Tracker or did you maybe refer to another doc?

**Comment by NicoHood** [comment]
Looks good to me!

**Comment by tsteur** [comment]
Thanks for mentioning @NicoHood  👍
