### ISSUE TITLE
disableCookieSupport() documentation clarification

### ISSUE THREAD

**Issue by NicoHood** [matomo-org/matomo-php-tracker#84]
I've also posted this question to the feedback button of the following page:
https://matomo.org/faq/general/faq_157/

---

Hey there!
I am using the matomo php API and I stumbled across the disableCookieSupport() function:
https://developer.matomo.org/api-reference/PHP-Matomo-Tracker#disablecookiesupport

Now to my observations this does not change anything, so I am wondering what this function will do. I wish that this gets more explained in the docs and optional here.

Also I've noticed that still 3 cookies are set:
* _pk_cvar.1.ceca
* _pk_id.1.ceca
* _pk_ses.1.ceca

Now I am wondering what those cookies are used for. They are not listed above in the docs, so I guess the page is outdated? Also I am wondering if the disabling of the cookie really worked, it seems it did not? Could you please clarify this to me via email, but also in the docs.

Thanks a lot!

**Comment by tsteur** [comment]
@NicoHood are you maybe calling the method `disableCookieSupport` after calling some other methods? It should work if you call it first thing and don't call `enableCookies`

**Comment by NicoHood** [comment]
It seems the browser did not cleanup the previos set cookies, so everything works now. Maybe it was also some kind of caching issue. I am really ashamed, that I've raised another invalid bug, sorry.
