### ISSUE TITLE
Licence Mismatch

### ISSUE THREAD

**Issue by exussum12** [matomo-org/matomo-php-tracker#93]
Composer suggests BSD-2-Clause

Licence File suggests 3 Clause, could one of them be updated so they match please ?

**Comment by sgiehl** [comment]
@tsteur @mattab Which license shall we use for this? The LICENSE files actually does not contain any specific license, but some custom content. the composer files includes BSD-2.

**Comment by Findus23** [comment]
@sgiehl The LICENSE file contains the three clause BSD license (https://opensource.org/licenses/BSD-3-Clause, recognicable as there are three clauses :slightly_smiling_face: ). Weirdly enough the phrase `of the copyright holder` is replaced with ` of the {organization} `.

Matomo also uses BSD-3 everywhere else (so for the matomo.js), so this might be what was originally intended.

**Comment by exussum12** [comment]
Github picks up thats its 3 clause also

![image](https://user-images.githubusercontent.com/1102850/118483456-ef2b9200-b70d-11eb-8a73-9ef2385484e2.png)


Looks like the json file needs adjusting then ?

![image](https://user-images.githubusercontent.com/1102850/118483530-05395280-b70e-11eb-9b8c-eb360cf0e41f.png)

**Comment by mattab** [comment]
Sounds good to use `The 3-Clause BSD License` (also called "New BSD")
